version: "3.8.0"

services:

  webserver:
    image: nginx:stable-perl
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./resource-service:/home/resource-service
      - ./users-service:/home/users-service
      - ./docker_resources/nginx/templates:/etc/nginx/templates/
      - ./docker_resources/nginx/nginx.conf:/etc/nginx/nginx.conf

    environment:
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}
      RESOURCE_SERVICE_PORT: ${APP_PORT}
    ports:
      - "80:80"
      - "9000:9000"

    depends_on:
      - resource-service
      - users-service


  resource-service:
    build:
      context: ./docker_resources/rust
      dockerfile: DockerFile

    image: inner_rust:v1
    container_name: resource-service
    restart: unless-stopped
    volumes:
      - ./resource-service:/home/resource-service/
      - ../rm_orm:/rm_orm
    environment:
      CMS_DB_USER: ${CMS_DB_USER}
      CMS_DB_PASS: ${CMS_DB_PASS}
      CMS_DB_HOST: ${CMS_DB_HOST}
      CMS_DB_PORT: ${CMS_DB_PORT}
      APP_HOST: 0.0.0.0
      APP_PORT: ${APP_PORT-6060}
      USERS_SERVICE_HOST: ${USERS_SERVICE_HOST}
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}

    ports:
      - "4050:${APP_PORT-6060}"
    expose:
      - ${APP_PORT-6060}
    command: bash -c "cd /home/resource-service && cargo watch -c -w src -x run "

    depends_on:
      - resource-service-db


  users-service:
    container_name: users-service
    restart: unless-stopped
    build:
      context: ./docker_resources/php
      dockerfile: Dockerfile
    image: inner_php:v1
    volumes:
      - ./users-service:/var/www/html
      - ./docker_resources/php/docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    user: root
    secrets:
      - source: cms_public_key
        target: cms_public_key
        gid: '33'
        uid: '33'
        mode: 777
      - source: cms_private_key
        target: cms_private_key
        gid: '33'
        uid: '33'
        mode: 777
    depends_on:
      - users-service-db

  resource-service-db:
    image: mongo:7.0.0-rc3-jammy
    container_name: resource-service-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CMS_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CMS_DB_PASS}
    volumes:
      - resource-service-db:/data/
    ports:
      - "${CMS_DB_PORT}:27017"

  users-service-db:
    image: mysql:8.0.33
    container_name: users-service-db
    restart: unless-stopped
    volumes:
      - users-service-db:/var/lib/mysql

    ports:
      - "${DB_PORT}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  resource-service-db:
  users-service-db:


secrets:
  cms_public_key:
    file: ${CMS_PUBLIC_KEY_PATH?error}

  cms_private_key:
    file: ${CMS_PRIVATE_KEY_PATH?error}